### ISSUE TITLE
GUI: Add button to play / pause the simulation in addition to hitting the space key.

### ISSUE THREAD

**Issue by procub3r** [acmpesuecc/gameoflife#1]
- The button can be of any size and placed anywhere.
- The button must have centered text displayed on it.
- You must increase the size of the window to accommodate for the button.

Let your creativity run wild! Make sure it looks decent :D

You must familiarize yourselves with how raylib works first. Head on over to https://www.raylib.com/examples.html to see some cool examples!

**Comment by Drakonxd786** [comment]
Can i get assigned to this?

**Comment by User-LazySloth** [comment]
Can you please assign this to me!

**Comment by ghost** [comment]
hey, can you pls assign this issue to me

**Comment by 7Akshu77** [comment]
Can I get assigned to this issue

**Comment by LalithaTanmayee** [comment]
Please assign this issue to me

**Comment by procub3r** [comment]
assigned to @sumukhacharya03 as he was the first to ask!

**Comment by pj1840** [comment]
can i be assigned to this

**Comment by procub3r** [comment]
> can i be assigned to this

I shall keep re-assigning the issue if the people in the queue don't deliver. Sit tight please!

**Comment by ProSai45** [comment]
Hey Can You Assign Me This Issue

**Comment by procub3r** [comment]
> Can I get assigned to this issue 

Would you like this issue to be assigned to you now?

**Comment by procub3r** [comment]
@7Akshu77 would like this issue to be assigned to you?

**Comment by 7Akshu77** [comment]
yes

**Comment by 7Akshu77** [comment]
what is the time block for this issue

**Comment by procub3r** [comment]
> what is the time block for this issue

@7Akshu77 one hour exactly. What is your progress?

**Comment by 411sst** [comment]
can i get assigned if this is still open?

**Comment by procub3r** [comment]
> can i get assigned if this is still open?

@ssether04 indeed! This issue has been assigned to you :D

**Comment by rahuljjacob** [comment]
can i please be assigned this issue  ?

**Comment by procub3r** [comment]
@ssether04 are you working on tgis, or shall I re-assign?

**Comment by procub3r** [comment]
@ssether04 i'm un-assigning this issue to you due to inactivity :D

**Comment by procub3r** [comment]
> can i please be assigned this issue  ? 

@rahuljjacob this issue has been assigned to you!

**Comment by User-LazySloth** [comment]
Hey! Could you please assign this to me!!

**Comment by procub3r** [comment]
@rahuljjacob are you still working on this issue?

**Comment by rahuljjacob** [comment]
yes :+1:
