### ISSUE TITLE
GUI: Add title text of the project in the GUI to let people know what they're looking at.

### ISSUE THREAD

**Issue by procub3r** [acmpesuecc/gameoflife#2]
- The text must be properly scaled (No blurry / weird text)
- It must be placed in an appropriate place (No hard restrictions)
- Change the window size to accommodate for the text.

Get as creative as you'd like with this!

**Comment by procub3r** [comment]
PS: I'm very particular about the font scaling.
You gotta earn those 20 points :D

**Comment by AkshayaR11** [comment]
Can i get assigned to this

**Comment by Drakonxd786** [comment]
can i get assigned to this?

**Comment by User-LazySloth** [comment]
Can you please assign this to me!

**Comment by 7Akshu77** [comment]
Can I get assigned to this issue

**Comment by procub3r** [comment]
assigned to @AkshayaR11 as he asked first!

**Comment by HemaShree0408** [comment]
can i get assigned

**Comment by procub3r** [comment]
> can i get assigned

If @AkshayaR11 doesn't acknowledge within a half hour, I shall assign it to the next person in queue, and so on.

**Comment by procub3r** [comment]
@AkshayaR11 I know it has been a while since you asked to be assigned, but please acknowledge that you'll be working on this :D
Else, it will be assigned to someone else.

**Comment by pj1840** [comment]
can i get assigned to this pls

**Comment by likhitharigela** [comment]
Can i get assigned to it pls

**Comment by procub3r** [comment]
@HemaShree0408 Would you like this issue to be assigned to you?

**Comment by HemaShree0408** [comment]
yes

**Comment by Lohithsurya** [comment]
can i get assigned to it

**Comment by procub3r** [comment]
@HemaShree0408 any updates on the issue?

**Comment by HemaShree0408** [comment]
u may assign it to the next person

**Comment by User-LazySloth** [comment]
Can you assign me this!

**Comment by 411sst** [comment]
can i get assigned if this is still open?

**Comment by procub3r** [comment]
> can i get assigned if this is still open?

@ssether04 I've assigned #1 to you :D

**Comment by procub3r** [comment]
> Can you assign me this!

@User-LazySloth this issue has been assigned to you!

**Comment by rahuljjacob** [comment]
Can I please be assigned to this issue ?

**Comment by procub3r** [comment]
@rahuljjacob This issue has been assigned to you!

**Comment by siri-n-shetty** [comment]
Could you please assign this to me?

**Comment by procub3r** [comment]
> Could you please assign this to me?

@siri-n-shetty this issue has been solved :D
It will be closed now.
